// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatanWalks.Data;

#nullable disable

namespace PatanWalks.Migrations
{
    [DbContext(typeof(MaharashtraDbContext))]
    [Migration("20230713151441_Seeding Data for Population")]
    partial class SeedingDataforPopulation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PatanWalks.Models.Domain.District", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AreaInSqKm")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistrictImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PopulationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DivisionId");

                    b.HasIndex("PopulationId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("PatanWalks.Models.Domain.Division", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DivisionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("PatanWalks.Models.Domain.Population", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CountOfPeople")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Populations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("771ee197-0f61-4fbf-994b-9772393fbbdc"),
                            CountOfPeople = 71820
                        },
                        new
                        {
                            Id = new Guid("45364c4e-4b50-4c58-9c12-ca95e3af1c18"),
                            CountOfPeople = 56374
                        },
                        new
                        {
                            Id = new Guid("482eba9f-42b0-452a-9b1d-5b16c9b97228"),
                            CountOfPeople = 10393
                        });
                });

            modelBuilder.Entity("PatanWalks.Models.Domain.District", b =>
                {
                    b.HasOne("PatanWalks.Models.Domain.Division", "Division")
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatanWalks.Models.Domain.Population", "Population")
                        .WithMany()
                        .HasForeignKey("PopulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("Population");
                });
#pragma warning restore 612, 618
        }
    }
}
